### ISSUE TITLE
Invalid JSON in docs/telemetry.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-cloudstorage#22]
```js
const {readFileSync} = require('fs');
const stripJsonComments = require('strip-json-comments');

try {
  const telemetry = readFileSync('./docs/telemetry.json', 'utf-8');
  const data = JSON.parse(stripJsonComments(telemetry));
  console.log(data);
} catch (err) {
  console.error(err);
}

// $ node telemetry.parser.js
//
// SyntaxError: Unexpected end of JSON input
//     at JSON.parse (<anonymous>)
//     at Object.<anonymous> (/Users/pdehaan/dev/github/mozilla/shield-cloudstorage/telemetry.parser.js:6:21)
//     at Module._compile (module.js:652:30)
//     at Object.Module._extensions..js (module.js:663:10)
//     at Module.load (module.js:565:32)
//     at tryModuleLoad (module.js:505:12)
//     at Function.Module._load (module.js:497:3)
//     at Function.Module.runMain (module.js:693:10)
//     at startup (bootstrap_node.js:188:16)
//     at bootstrap_node.js:609:3

```

**Comment by punamdahiya** [comment]
PR updated with fix. Thanks!
